
------------BORRADO DE SECUENCIAS--------------
  
DROP SEQUENCE sec_clientes;
DROP SEQUENCE sec_empleados;
DROP SEQUENCE sec_servicios;
DROP SEQUENCE sec_facturas;
DROP SEQUENCE sec_pedidos;
DROP SEQUENCE sec_gastos;


------------BORRADO DE TABLAS--------------
DROP TABLE Pedidos;
DROP TABLE Clientes;
DROP TABLE Empleados;
DROP TABLE Servicios;
DROP TABLE Facturas;
DROP TABLE Gastos;


------------CREACION DE TABLAS--------------
CREATE TABLE Clientes(
  OID_C INTEGER NOT NULL,
  Nombre VARCHAR2(50) NOT NULL,
  Direccion VARCHAR2(50),
  NumeroTelefono VARCHAR2(9) NOT NULL,
  CorreoElectronico VARCHAR2(60) NOT NULL,
  PRIMARY KEY(OID_C),
  UNIQUE(CorreoElectronico)
  );
  

CREATE TABLE Empleados(
  OID_E INTEGER NOT NULL,
  NombreE VARCHAR2(50) NOT NULL,
  TipoCamion VARCHAR2(20) NOT NULL, CONSTRAINT "TIPOCAMION_CHK1" CHECK (TipoCamion IN('Camion','Camion_Grua')),
  PRIMARY KEY(OID_E)
  );
  

CREATE TABLE Servicios(
  OID_S INTEGER NOT NULL,
  TipoServicio VARCHAR2(25) NOT NULL, CONSTRAINT "TIPOSERVICIO_CHK2" CHECK (TipoServicio IN('CUBA_ESCOMBROS','CUBA_PODA','CUBA_ESTIERCOL','OTRO_MATERIALES','LEÑA','GRUA','ESPECIAL','ARIDOS')),
  DistanciaKM INTEGER, CONSTRAINT "DISTANCIA_CHK5" CHECK (DistanciaKM<=35),
  HorasGrua INTEGER,
  TamañoCuba VARCHAR2(10), CONSTRAINT "TAMAÑOCUBA_CHK3" CHECK (TamañoCuba IN('PEQUEÑA','MEDIANA','GRANDE')),
  PesoKG INTEGER, CONSTRAINT "PesoKG" CHECK (PesoKG<4500),
  VolumenM3 INTEGER, CONSTRAINT "VOLUMENM3_CHK7" CHECK (VolumenM3<=5),
  PRIMARY KEY(OID_S)
  );

CREATE TABLE Facturas(
  OID_F INTEGER NOT NULL,
  FechaEmision DATE, CONSTRAINT "FECHAEMISON_CHK6" CHECK (FechaEmision > FechaCreacion),
  NumPedidos INTEGER NOT NULL,
  PrecioSinIva NUMBER(38,2) NOT NULL,
  PrecioTotal NUMBER(38,2) NOT NULL,
  EstaPagado CHAR(2) NOT NULL, CONSTRAINT "ESTAPAGADO_CHK4"CHECK (EstaPagado IN('SI','NO')),
  FechaCreacion DATE DEFAULT SYSDATE,
  PRIMARY KEY(OID_F)
  );

CREATE TABLE Gastos(
  OID_G INTEGER NOT NULL,
  Nombre VARCHAR2(50) NOT NULL,
  Descripcion VARCHAR2(70) NOT NULL,
  Coste NUMBER(38,2) NOT NULL,
  IVA NUMBER(38,2) NOT NULL,
  FechaPago DATE NOT NULL,
  FechaInicio DATE NOT NULL,
  FechaFin DATE NOT NULL, CONSTRAINT "FECHAFIN_CHK8" CHECK (FechaInicio<=FechaFin),
  PRIMARY KEY(OID_G)
  );
  

CREATE TABLE Pedidos(
  OID_P INTEGER NOT NULL,
  Precio NUMBER(6,2) NOT NULL,
  Direccion VARCHAR(50) NOT NULL,
  Fecha DATE NOT NULL,
  OID_C INTEGER NOT NULL,
  OID_E INTEGER NOT NULL,
  OID_S INTEGER NOT NULL,
  OID_F INTEGER NOT NULL,

  PRIMARY KEY(OID_P),
  FOREIGN KEY(OID_C) REFERENCES Clientes,
  FOREIGN KEY(OID_E) REFERENCES Empleados,
  FOREIGN KEY(OID_S) REFERENCES Servicios,
  FOREIGN KEY(OID_F) REFERENCES Facturas
  );


  
------------CREACION DE SECUENCIAS--------------
  
CREATE SEQUENCE sec_clientes;
CREATE OR REPLACE TRIGGER crea_oid_c BEFORE INSERT ON Clientes
FOR EACH ROW
BEGIN
	SELECT sec_clientes.NEXTVAL INTO :NEW.OID_C FROM DUAL;
END;
/


CREATE SEQUENCE sec_empleados;
CREATE OR REPLACE TRIGGER crea_oid_e BEFORE INSERT ON Empleados
FOR EACH ROW
BEGIN
	SELECT sec_empleados.NEXTVAL INTO :NEW.OID_E FROM DUAL;
END;
/

CREATE SEQUENCE sec_servicios;
CREATE OR REPLACE TRIGGER crea_oid_s BEFORE INSERT ON Servicios
FOR EACH ROW
BEGIN
	SELECT sec_servicios.NEXTVAL INTO :NEW.OID_S FROM DUAL;
END;
/


CREATE SEQUENCE sec_facturas;
CREATE OR REPLACE TRIGGER crea_oid_f BEFORE INSERT ON Facturas
FOR EACH ROW
BEGIN
	SELECT sec_facturas.NEXTVAL INTO :NEW.OID_F FROM DUAL;
END;
/


CREATE SEQUENCE sec_gastos;
CREATE OR REPLACE TRIGGER crea_oid_g BEFORE INSERT ON Gastos
FOR EACH ROW
BEGIN
	SELECT sec_gastos.NEXTVAL INTO :NEW.OID_G FROM DUAL;
END;
/


CREATE SEQUENCE sec_pedidos;
CREATE OR REPLACE TRIGGER crea_oid_p BEFORE INSERT ON Pedidos
FOR EACH ROW
BEGIN
	SELECT sec_pedidos.NEXTVAL INTO :NEW.OID_P FROM DUAL;
END;
/