
--------------------------------------------------------------------------------------------EJECUCIÓN PRUEBAS------------------------------------------------------------------------

SET SERVEROUTPUT ON;

DECLARE
COD_GASTOS INTEGER;

COD_PEDIDOS INTEGER;
COD_CLIENTES_PRUEBA INTEGER;
COD_EMPLEADOS_PRUEBA INTEGER;
COD_SERVICIOS_PRUEBA INTEGER;

COD_CLIENTES INTEGER;

COD_FACTURAS INTEGER;

COD_EMPLEADOS INTEGER;

COD_SERVICIOS INTEGER;



BEGIN

----------------------------------------------------------------PRUEBAS GASTOS

PRUEBAS_GASTOS.INICIALIZAR;

PRUEBAS_GASTOS.INSERTAR('PRUEBA 1 - INSERCIÓN GASTOS', 'Gasoil', 'Pago de gasoil', 500, '21/1/2015', '1/1/15', '31/1/15', true);
COD_GASTOS:= SEC_GASTOS.CURRVAL;

PRUEBAS_GASTOS.INSERTAR('PRUEBA 2 - INSERCIÓN GASTOS nombre en null', null, 'Pago de gasoil', 500, '21/1/2015', '1/1/15', '31/1/15', false);
PRUEBAS_GASTOS.INSERTAR('PRUEBA 3 - INSERCIÓN GASTOS descripcion null', 'Gasoil', null, 500, '21/1/2015', '1/1/15', '31/1/15', false);
PRUEBAS_GASTOS.INSERTAR('PRUEBA 4 - INSERCIÓN GASTOS coste null', 'Gasoil', 'Pago de gasoil', null, '21/1/2015', '1/1/15', '31/1/15', false);
PRUEBAS_GASTOS.INSERTAR('PRUEBA 5 - INSERCIÓN GASTOS fecha pago null', 'Gasoil', 'Pago de gasoil', 500, null, '1/1/15', '31/1/15', false);
PRUEBAS_GASTOS.INSERTAR('PRUEBA 6 - INSERCIÓN GASTOS fecha inicio null', 'Gasoil', 'Pago de gasoil', 500, '21/1/2015', null, '31/1/15', false);
PRUEBAS_GASTOS.INSERTAR('PRUEBA 7 - INSERCIÓN GASTOS fecha fin null', 'Gasoil', 'Pago de gasoil', 500, '21/1/2015', '1/1/15', null, false);
PRUEBAS_GASTOS.INSERTAR('PRUEBA 8 - INSERCIÓN GASTOS fecha fin antes que fecha inicio', 'Gasoil', 'Pago de gasoil', 500, '21/1/2015', '1/2/15', '31/1/15', false);


PRUEBAS_GASTOS.actualizar('PRUEBA 9 - ACTUALIZACIÓN GASTOS',COD_GASTOS, 'Gasolina', 'Pago de gasolina', 600, '21/1/2016', '1/1/16', '31/1/16', true);


PRUEBAS_GASTOS.actualizar('PRUEBA 10 - ACTUALIZACIÓN GASTOS nombre en null', COD_GASTOS, null, 'Pago de gasoil', 500, '21/1/2015', '1/1/15', '31/1/15', false);
PRUEBAS_GASTOS.actualizar('PRUEBA 11 - ACTUALIZACIÓN GASTOS descripcion null',COD_GASTOS, 'Gasoil', null, 500, '21/1/2015', '1/1/15', '31/1/15', false);
PRUEBAS_GASTOS.actualizar('PRUEBA 12 - ACTUALIZACIÓN GASTOS coste null',COD_GASTOS, 'Gasoil', 'Pago de gasoil', null, '21/1/2015', '1/1/15', '31/1/15', false);
PRUEBAS_GASTOS.actualizar('PRUEBA 13 - ACTUALIZACIÓN GASTOS fecha pago null',COD_GASTOS, 'Gasoil', 'Pago de gasoil', 500, null, '1/1/15', '31/1/15', false);
PRUEBAS_GASTOS.actualizar('PRUEBA 14 - ACTUALIZACIÓN GASTOS fecha inicio null',COD_GASTOS, 'Gasoil', 'Pago de gasoil', 500, '21/1/2015', null, '31/1/15', false);
PRUEBAS_GASTOS.actualizar('PRUEBA 15 - ACTUALIZACIÓN GASTOS fin null',COD_GASTOS, 'Gasoil', 'Pago de gasoil', 500, '21/1/2015', '1/1/15', null, false);
PRUEBAS_GASTOS.actualizar('PRUEBA 16 - ACTUALIZACIÓN GASTOS fecha fin antes que fecha inicio',COD_GASTOS, 'Gasoil', 'Pago de gasoil', 500, '21/1/2015', '1/2/15', '31/1/15', false);
PRUEBAS_GASTOS.actualizar('PRUEBA 17 - ACTUALIZACIÓN GASTOS oid_g a null',null, 'Gasoil', 'Pago de gasoil', 500, '21/1/2015', '1/1/15', '31/1/15', false);

PRUEBAS_GASTOS.ELIMINAR('PRUEBA 18 - ELIMINACIÓN GASTOS', COD_GASTOS, true);


----------------------------------------------------------------PRUEBAS CLIENTES

PRUEBAS_CLIENTES.INICIALIZAR;
PRUEBAS_CLIENTES.INSERTAR('PRUEBA 1 - INSERCIÓN CLIENTES buena', 'Juan', 'C/Clavel s/n', '123456789', 'juan@prueba.com', true);
COD_CLIENTES:= sec_clientes.currval;
PRUEBAS_CLIENTES.INSERTAR('PRUEBA 1.2 - INSERCIÓN CLIENTES buena', 'Juan', 'C/Clavel s/n', '123456789', 'juan2@prueba.com', true);


PRUEBAS_CLIENTES.INSERTAR('PRUEBA 2 - INSERCIÓN CLIENTES nombre a null', null, 'C/Clavel s/n', '123456789', 'juan@prueba.com', false);
PRUEBAS_CLIENTES.INSERTAR('PRUEBA 3 - INSERCIÓN CLIENTES telefono a null', 'Juan', 'C/Clavel s/n', null, 'juan@prueba.com', false);
PRUEBAS_CLIENTES.INSERTAR('PRUEBA 4 - INSERCIÓN CLIENTES correo a null', 'Juan', 'C/Clavel s/n', '123456789', null, false);
PRUEBAS_CLIENTES.INSERTAR('PRUEBA 5 - INSERCIÓN CLIENTES mismo correo', 'Juan', 'C/Clavel s/n', '123456789', 'juan@prueba.com', false);

PRUEBAS_CLIENTES.ACTUALIZAR('PRUEBA 6  - ACTUALIZACIÓN CLIENTES', COD_CLIENTES, 'Juan Andres', 'C/Clavel 6', '223456789', 'juanito@prueba.com', true);
PRUEBAS_CLIENTES.ACTUALIZAR('PRUEBA 7  - ACTUALIZACIÓN CLIENTES oid_c a null', null, 'Juan Andres', 'C/Clavel 6', '223456789', 'juan2@prueba.com', false);
PRUEBAS_CLIENTES.ACTUALIZAR('PRUEBA 8  - ACTUALIZACIÓN CLIENTES nombre a null', COD_CLIENTES, null, 'C/Clavel s/n', '123456789', 'juan@prueba.com', false);
PRUEBAS_CLIENTES.ACTUALIZAR('PRUEBA 9  - ACTUALIZACIÓN CLIENTES telefono a null', COD_CLIENTES, 'Juan Andres', 'C/Clavel s/n', null, 'juan@prueba.com', false);
PRUEBAS_CLIENTES.ACTUALIZAR('PRUEBA 10  - ACTUALIZACIÓN CLIENTES correo a null', COD_CLIENTES, 'Juan Andres', 'C/Clavel s/n', '123456789', null, false);
PRUEBAS_CLIENTES.ACTUALIZAR('PRUEBA 11  - ACTUALIZACIÓN CLIENTES mismo correo', COD_CLIENTES, 'Juan Andres', 'C/Clavel s/n', '123456789', 'juan2@prueba.com', false);

PRUEBAS_CLIENTES.ELIMINAR('PRUEBA 12 - ELIMINACIÓN CLIENTES', COD_CLIENTES, true);


----------------------------------------------------------------PRUEBAS FACTURAS


PRUEBAS_FACTURAS.INICIALIZAR;
PRUEBAS_FACTURAS.INSERTAR('PRUEBA 1 - INSERCIÓN FACTURA buena', 4, 140, 'NO', '21/1/2018', true);
COD_FACTURAS:= sec_facturas.currval;

PRUEBAS_FACTURAS.INSERTAR('PRUEBA 2 - INSERCIÓN FACTURA fecha emision antes fecha creacion', 4, 140, 'SI', '21/1/2018', false);
PRUEBAS_FACTURAS.INSERTAR('PRUEBA 3 - INSERCIÓN FACTURA numero pedidos a null', null, 140, 'SI', '21/1/2012', false);
PRUEBAS_FACTURAS.INSERTAR('PRUEBA 4 - INSERCIÓN FACTURA esta pagado a null', 4, 140, null, '21/1/2018', false);
PRUEBAS_FACTURAS.INSERTAR('PRUEBA 5 - INSERCIÓN FACTURA esta pagado invalido', 4, 140, 'moroso', '21/1/2018', false);
PRUEBAS_FACTURAS.INSERTAR('PRUEBA 6 - INSERCIÓN FACTURA precio a null', 4, null, 'SI', '21/1/2018', false);


PRUEBAS_FACTURAS.ACTUALIZAR('PRUEBA 6 - ACTUALIZACION FACTURA buena', COD_FACTURAS, 3, 140, 'NO', '10/6/2018', true);
PRUEBAS_FACTURAS.ACTUALIZAR('PRUEBA 7 - ACTUALIZACION FACTURA oid_f a null', null, 3, 140, 'SI', '10/6/2018', false);
PRUEBAS_FACTURAS.ACTUALIZAR('PRUEBA 8 - ACTUALIZACION FACTURA fecha emision antes fecha creacion', COD_FACTURAS, 3, 140, 'SI', '10/6/2018', false);
PRUEBAS_FACTURAS.ACTUALIZAR('PRUEBA 9 - ACTUALIZACION FACTURA esta pagado a null', COD_FACTURAS, 3, 140, null, '10/6/2018', false);
PRUEBAS_FACTURAS.ACTUALIZAR('PRUEBA 10 - ACTUALIZACION FACTURA esta pagado invalido', COD_FACTURAS, 3, 140, 'moroso', '10/6/2018', false);
PRUEBAS_FACTURAS.ACTUALIZAR('PRUEBA 11 - ACTUALIZACION FACTURA precio a null',COD_FACTURAS, 4, null, 'SI', '21/1/2018', false);

PRUEBAS_FACTURAS.ELIMINAR('PRUEBA 12 - ELIMINACIÓN CLIENTES', COD_FACTURAS, true);


----------------------------------------------------------------PRUEBAS EMPLEADOS


PRUEBAS_EMPLEADOS.INICIALIZAR;

PRUEBAS_EMPLEADOS.INSERTAR('PRUEBA 1 - INSERCIÓN EMPLEADOS', 'Paco' , 'Camion', true);
COD_EMPLEADOS:=SEC_EMPLEADOS.CURRVAL;

PRUEBAS_EMPLEADOS.INSERTAR('PRUEBA 2 - INSERCIÓN EMPLEADOS - Nombre empleado a null', null , 'Camion', false);
PRUEBAS_EMPLEADOS.INSERTAR('PRUEBA 3 - INSERCIÓN EMPLEADOS - Tipo camion a null ', 'Paco' , null, false);
PRUEBAS_EMPLEADOS.INSERTAR('PRUEBA 4 - INSERCIÓN EMPLEADOS - Tipo camion inválido', 'Paco' , 'Tractor', false);

PRUEBAS_EMPLEADOS.ACTUALIZAR('PRUEBA 5 - ACTUALIZACIÓN EMPLEADOS', COD_EMPLEADOS, 'Manuel', 'Camion_Grua', true);
PRUEBAS_EMPLEADOS.ACTUALIZAR('PRUEBA 6 - ACTUALIZACIÓN EMPLEADOS - Nombre empleado a null', COD_EMPLEADOS, null, 'Camion_Grua', false);
PRUEBAS_EMPLEADOS.ACTUALIZAR('PRUEBA 7 - ACTUALIZACIÓN EMPLEADOS - Tipo camion a null', COD_EMPLEADOS, 'Manuel', null, false);
PRUEBAS_EMPLEADOS.ACTUALIZAR('PRUEBA 8 - ACTUALIZACIÓN EMPLEADOS - Tipo camion inválido', COD_EMPLEADOS, 'Manuel', 'Tractor', false);

PRUEBAS_EMPLEADOS.ELIMINAR('PRUEBA 9 - ELIMINACIÓN EMPLEADOS',COD_EMPLEADOS,TRUE);


----------------------------------------------------------------PRUEBAS SERVICIOS

PRUEBAS_SERVICIOS.INICIALIZAR;

PRUEBAS_SERVICIOS.INSERTAR('PRUEBA 1 - INSERCIÓN SERVICIOS', 'CUBA_ESCOMBROS', 30, NULL, 'PEQUEÑA', NULL,NULL, TRUE);
COD_SERVICIOS:=SEC_SERVICIOS.CURRVAL;

PRUEBAS_SERVICIOS.INSERTAR('PRUEBA 2 - INSERCIÓN SERVICIOS - Tipo servicio null', NULL, 30, NULL, 'PEQUEÑA', NULL,NULL, FALSE);
PRUEBAS_SERVICIOS.INSERTAR('PRUEBA 2 - INSERCIÓN SERVICIOS - Tipo servicio inválido', 'PRIEDRA_CALIZA', 30, NULL, 'PEQUEÑA', NULL,NULL, FALSE);
PRUEBAS_SERVICIOS.INSERTAR('PRUEBA 3 - INSERCIÓN SERVICIOS - Distancia mayor de 35 km', 'CUBA_ESCOMBROS', 40, NULL, 'PEQUEÑA', NULL,NULL, FALSE);
PRUEBAS_SERVICIOS.INSERTAR('PRUEBA 4 - INSERCIÓN SERVICIOS - Tamaño cuba inválido', 'CUBA_ESCOMBROS', 30, NULL, 'MUY GRANDE', NULL,NULL, FALSE);
PRUEBAS_SERVICIOS.INSERTAR('PRUEBA 5 - INSERCIÓN SERVICIOS - Peso mayor de 4500', 'LEÑA', NULL, NULL, NULL, 5000,NULL, FALSE);
PRUEBAS_SERVICIOS.INSERTAR('PRUEBA 6 - INSERCIÓN SERVICIOS - Volumen mayor de 5 m3', 'ÁRIDOS', 30, NULL, NULL, NULL, 7, FALSE);

PRUEBAS_SERVICIOS.ACTUALIZAR('PRUEBA 7 - ACTUALIZACIÓN SERVICIOS', COD_SERVICIOS, 'CUBA_PODA', 30, NULL, 'PEQUEÑA', NULL,NULL, TRUE);
PRUEBAS_SERVICIOS.ACTUALIZAR('PRUEBA 8 - ACTUALIZACIÓN SERVICIOS - Tipo servicio null', COD_SERVICIOS, NULL, 30, NULL, 'PEQUEÑA', NULL,NULL, FALSE);
PRUEBAS_SERVICIOS.ACTUALIZAR('PRUEBA 9 - ACTUALIZACIÓN SERVICIOS - Tipo servicio inválido', COD_SERVICIOS, 'PRIEDRA_CALIZA', 30, NULL, 'PEQUEÑA', NULL,NULL, FALSE);
PRUEBAS_SERVICIOS.ACTUALIZAR('PRUEBA 10 - ACTUALIZACIÓN SERVICIOS - Distancia mayor de 35 km', COD_SERVICIOS, 'CUBA_ESCOMBROS', 40, NULL, 'PEQUEÑA', NULL,NULL, FALSE);
PRUEBAS_SERVICIOS.ACTUALIZAR('PRUEBA 11 - ACTUALIZACIÓN SERVICIOS - Tamaño cuba inválido', COD_SERVICIOS, 'CUBA_ESCOMBROS', 30, NULL, 'MUY GRANDE', NULL,NULL, FALSE);
PRUEBAS_SERVICIOS.ACTUALIZAR('PRUEBA 12 - ACTUALIZACIÓN SERVICIOS - Peso mayor de 4500', COD_SERVICIOS, 'LEÑA', NULL, NULL, NULL, 5000,NULL, FALSE);
PRUEBAS_SERVICIOS.ACTUALIZAR('PRUEBA 13 - ACTUALIZACIÓN SERVICIOS - Volumen mayor de 5 m3', COD_SERVICIOS, 'ÁRIDOS', 30, NULL, NULL, NULL, 7, FALSE);

PRUEBAS_SERVICIOS.ELIMINAR('PRUEBA 14 - ELIMINACIÓN SERVICIOS', COD_SERVICIOS, TRUE);



----------------------------------------------------------------PRUEBAS PEDIDOS

PRUEBAS_CLIENTES.INICIALIZAR;
INSERT INTO CLIENTES(NOMBRE, DIRECCION, NUMEROTELEFONO, CORREOELECTRONICO) VALUES('Juan', 'C/Clavel s/n', '123456789', 'orion@prueba.com');
COD_clientes_PRUEBA :=SEC_CLIENTES.CURRVAL;

PRUEBAS_EMPLEADOS.INICIALIZAR;
INSERT INTO EMPLEADOS(NOMBREE, TIPOCAMION) VALUES('PACO', 'Camion');
COD_EMPLEADOS_PRUEBA:=SEC_EMPLEADOS.CURRVAL;


PRUEBAS_SERVICIOS.INICIALIZAR;
INSERT INTO SERVICIOS(TIPOSERVICIO, DISTANCIAKM, HORASGRUA, TAMAÑOCUBA, PESOKG, VOLUMENM3) VALUES ('CUBA_ESCOMBROS', 30, NULL, 'PEQUEÑA', NULL,NULL);
COD_SERVICIOS_PRUEBA:=SEC_SERVICIOS.CURRVAL;

PRUEBAS_PEDIDOS.INICIALIZAR;

PRUEBAS_PEDIDOS.INSERTAR('PRUEBA 1 - INSERCIÓN PEDIDOS', 500, 'CALLE LUIS DAOIZ', '20/09/14', COD_CLIENTES_PRUEBA, COD_EMPLEADOS_PRUEBA, COD_SERVICIOS_PRUEBA, true);
COD_PEDIDOS:= SEC_PEDIDOS.CURRVAL;

PRUEBAS_PEDIDOS.INSERTAR('PRUEBA 2 - INSERCIÓN PEDIDOS precio null', NULL, 'CALLE LUIS DAOIZ', '20/09/14', COD_CLIENTES_PRUEBA, COD_EMPLEADOS_PRUEBA, COD_SERVICIOS_PRUEBA, false);
PRUEBAS_PEDIDOS.INSERTAR('PRUEBA 3 - INSERCIÓN PEDIDOS dirección null', 500, NULL, '20/09/14', COD_CLIENTES_PRUEBA, COD_EMPLEADOS_PRUEBA, COD_SERVICIOS_PRUEBA, false);
PRUEBAS_PEDIDOS.INSERTAR('PRUEBA 4 - INSERCIÓN PEDIDOS fecha null', 500, 'CALLE LUIS DAOIZ', NULL, COD_CLIENTES_PRUEBA, COD_EMPLEADOS_PRUEBA, COD_SERVICIOS_PRUEBA, false);
PRUEBAS_PEDIDOS.INSERTAR('PRUEBA 5 - INSERCIÓN PEDIDOS oid_c null', 500, 'CALLE LUIS DAOIZ', '20/09/14', NULL, COD_EMPLEADOS_PRUEBA, COD_SERVICIOS_PRUEBA, false);
PRUEBAS_PEDIDOS.INSERTAR('PRUEBA 6 - INSERCIÓN PEDIDOS oid_e null', 500, 'CALLE LUIS DAOIZ', '20/09/14', COD_CLIENTES_PRUEBA, NULL, COD_SERVICIOS_PRUEBA, false);
PRUEBAS_PEDIDOS.INSERTAR('PRUEBA 7 - INSERCIÓN PEDIDOS oid_s null', 500, 'CALLE LUIS DAOIZ', '20/09/14', COD_CLIENTES_PRUEBA, COD_EMPLEADOS_PRUEBA, NULL, false);

PRUEBAS_PEDIDOS.ACTUALIZAR('PRUEBA 8 - ACTUALIZACIÓN PEDIDOS', COD_PEDIDOS, 600, 'CALLE LUIS MONTOTO', '20/09/15', COD_CLIENTES_PRUEBA, COD_EMPLEADOS_PRUEBA, COD_SERVICIOS_PRUEBA, true);

PRUEBAS_PEDIDOS.ACTUALIZAR('PRUEBA 9 - ACTUALIZACIÓN PEDIDOS precio null', COD_PEDIDOS,NULL, 'CALLE LUIS DAOIZ', '20/09/14', COD_CLIENTES_PRUEBA, COD_EMPLEADOS_PRUEBA, COD_SERVICIOS_PRUEBA, false);
PRUEBAS_PEDIDOS.ACTUALIZAR('PRUEBA 10 - ACTUALIZACIÓN PEDIDOS dirección null', COD_PEDIDOS,500, NULL, '20/09/14', COD_CLIENTES_PRUEBA, COD_EMPLEADOS_PRUEBA, COD_SERVICIOS_PRUEBA, false);
PRUEBAS_PEDIDOS.ACTUALIZAR('PRUEBA 11 - ACTUALIZACIÓN PEDIDOS fecha null', COD_PEDIDOS,500, 'CALLE LUIS DAOIZ', NULL, COD_CLIENTES_PRUEBA, COD_EMPLEADOS_PRUEBA, COD_SERVICIOS_PRUEBA, false);
PRUEBAS_PEDIDOS.ACTUALIZAR('PRUEBA 12 - ACTUALIZACIÓN PEDIDOS oid_c null', COD_PEDIDOS,500, 'CALLE LUIS DAOIZ', '20/09/14', NULL, COD_EMPLEADOS_PRUEBA, COD_SERVICIOS_PRUEBA, false);
PRUEBAS_PEDIDOS.ACTUALIZAR('PRUEBA 13 - ACTUALIZACIÓN PEDIDOS oid_e null', COD_PEDIDOS,500, 'CALLE LUIS DAOIZ', '20/09/14', COD_CLIENTES_PRUEBA, NULL, COD_SERVICIOS_PRUEBA, false);
PRUEBAS_PEDIDOS.ACTUALIZAR('PRUEBA 14 - ACTUALIZACIÓN PEDIDOS oid_s null', COD_PEDIDOS,500, 'CALLE LUIS DAOIZ', '20/09/14', COD_CLIENTES_PRUEBA, COD_EMPLEADOS_PRUEBA, NULL, false);

PRUEBAS_PEDIDOS.ELIMINAR('PRUEBA 15 - ELIMINACIÓN PEDIDOS', COD_PEDIDOS, true);




END;

	
