----------------------------------------FUNCIONES INSERTAR DATOS-------------------------------

CREATE OR REPLACE PROCEDURE INSERTAR_PEDIDO 
  (P_PRECIO IN PEDIDOS.PRECIO%TYPE,
   P_DIRECCION IN PEDIDOS.DIRECCION%TYPE,
   P_FECHA IN PEDIDOS.FECHA%TYPE,
   P_OID_C IN PEDIDOS.OID_C%TYPE,
   P_OID_E IN PEDIDOS.OID_E%TYPE,
   P_OID_S IN PEDIDOS.OID_S%TYPE) IS
BEGIN
  INSERT INTO PEDIDOS(Precio, Direccion, Fecha, OID_C, OID_E, OID_S) 
  VALUES (P_PRECIO,P_DIRECCION, P_FECHA, P_OID_C, P_OID_E, P_OID_S);
END;
/


CREATE OR REPLACE PROCEDURE INSERTAR_EMPLEADO 
  (P_NOMBREE IN EMPLEADOS.NOMBREE%TYPE,
   P_CAMION IN EMPLEADOS.TipoCamion%TYPE) IS
BEGIN
  INSERT INTO EMPLEADOS(Nombree, TipoCamion) 
  VALUES (P_NOMBREE, P_CAMION);
END;
/

CREATE OR REPLACE PROCEDURE INSERTAR_CLIENTE 
  (P_NOMBRE IN CLIENTES.NOMBRE%TYPE,
   P_DIRECCION IN CLIENTES.DIRECCION%TYPE,
   P_TELEFONO IN CLIENTES.NUMEROTELEFONO%TYPE,
   P_CORREO IN CLIENTES.CORREOELECTRONICO%TYPE) IS
BEGIN
  INSERT INTO CLIENTES (Nombre, Direccion, NumeroTelefono, CorreoElectronico)
  VALUES (P_NOMBRE,P_DIRECCION, P_TELEFONO, P_CORREO);
END;
/

CREATE OR REPLACE PROCEDURE INSERTAR_SERVICIO
  (P_TIPO IN SERVICIOS.TIPOSERVICIO%TYPE,
   P_DISTANCIA IN SERVICIOS.DISTANCIAKM%TYPE,
   P_HORAS IN SERVICIOS.HORASGRUA%TYPE,
   P_TAMANO IN SERVICIOS.TAMAÑOCUBA%TYPE,
   P_PESO IN SERVICIOS.PESOKG%TYPE) IS
BEGIN
  INSERT INTO SERVICIOS (TipoServicio, DistanciaKM, HorasGrua, TamañoCuba, PesoKG)
  VALUES (P_TIPO,P_DISTANCIA, P_HORAS, P_TAMANO, P_PESO);
END;
/